# Generated by Django 5.0 on 2024-01-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_model', '0002_rename_assigndata_taskmodel_assigndate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('taskModel', models.ManyToManyField(to='task_model.taskmodel')),
            ],
        ),
    ]
