# Generated by Django 5.0 on 2024-01-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='assignData',
            new_name='assignDate',
        ),
    ]
